# Generated by Django 2.1.4 on 2019-01-27 10:41

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='不允许与其他条目重复。', max_length=25, unique=True, verbose_name='名称')),
                ('timeModify', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='修改时间')),
                ('timeCreate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('markdownBody', models.TextField(blank=True, default=' ', verbose_name='正文')),
                ('timePublish', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('status', models.BooleanField(default=False, verbose_name='发布状态')),
                ('body', models.TextField(blank=True, default=' ', editable=False)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'permissions': (('publish_article', 'Can publish 文章'),),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='不允许与其他条目重复。', max_length=25, unique=True, verbose_name='名称')),
                ('timeModify', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='修改时间')),
                ('timeCreate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('level', models.PositiveIntegerField(default=0, editable=False, verbose_name='等级')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('group', models.ForeignKey(blank=True, help_text='组内用户有此条目下文章的编辑权限。', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='组')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='若上级目录为空，则此目录为顶级目录。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Category', verbose_name='上级目录')),
                ('userCreate', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('userModify', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '目录',
                'verbose_name_plural': '目录',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='不允许与其他条目重复。', max_length=25, unique=True, verbose_name='名称')),
                ('timeModify', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='修改时间')),
                ('timeCreate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('file', models.FileField(upload_to=blog.models.storage_redirect, verbose_name='文件')),
                ('url', models.CharField(blank=True, editable=False, max_length=64, verbose_name='访问路径')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='文章')),
                ('userCreate', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('userModify', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='userCreate',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='article',
            name='userModify',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改者'),
        ),
    ]
