# Generated by Django 2.1.4 on 2019-01-21 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190121_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='timePublish',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 24, 24, 937514, tzinfo=utc), verbose_name='发布时间'),
            preserve_default=False,
        ),
    ]
