# Generated by Django 2.1.4 on 2019-01-23 15:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20190123_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='painter',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='painter', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='picture',
            name='timeCreate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 15, 25, 22, 175466, tzinfo=utc), editable=False, verbose_name='创建时间'),
        ),
    ]
