# Generated by Django 2.1.4 on 2019-01-23 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190124_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='timeModify',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次修改时间'),
        ),
    ]
