# Generated by Django 2.1.4 on 2019-02-11 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enroll.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSubmit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(blank=True, max_length=256, verbose_name='密码')),
            ],
            options={
                'verbose_name': '答卷',
                'verbose_name_plural': '答卷',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='选项')),
                ('description', models.CharField(max_length=256, verbose_name='选项内容')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FileAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to=enroll.models.answer_redirect, verbose_name='附件')),
                ('answerSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.AnswerSheet', verbose_name='答卷')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeModify', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='修改时间')),
                ('timeCreate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('order', models.IntegerField(default=1, verbose_name='题号')),
                ('type', models.IntegerField(choices=[[1, '单选题'], [2, '多选题'], [3, '填空题'], [4, '文件题']], default=1, verbose_name='题型')),
                ('require', models.BooleanField(default=False, verbose_name='必答')),
                ('description', models.TextField(blank=True, verbose_name='题目')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeModify', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='修改时间')),
                ('timeCreate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('name', models.CharField(help_text='不允许与其他条目重复。', max_length=25, verbose_name='名称')),
                ('status', models.BooleanField(default=False, verbose_name='发布状态')),
                ('timePublish', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('deadLine', models.DateTimeField(null=True, verbose_name='截止时间')),
                ('email', models.EmailField(max_length=254, verbose_name='客服邮箱')),
                ('userCreate', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll_questionnaire_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('userModify', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll_questionnaire_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeModify', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='修改时间')),
                ('timeCreate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='名称')),
                ('file', models.FileField(upload_to=enroll.models.resource_redirect, verbose_name='文件')),
                ('url', models.CharField(blank=True, editable=False, max_length=64, verbose_name='访问路径')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.Questionnaire', verbose_name='问卷')),
                ('userCreate', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll_resource_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('userModify', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll_resource_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
            },
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='答案')),
                ('answerSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.AnswerSheet', verbose_name='答卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.Question', verbose_name='问题')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.Questionnaire', verbose_name='问卷'),
        ),
        migrations.AddField(
            model_name='question',
            name='userCreate',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll_question_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='question',
            name='userModify',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll_question_modified', to=settings.AUTH_USER_MODEL, verbose_name='修改者'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.Question', verbose_name='问题'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.Question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.Questionnaire', verbose_name='问卷'),
        ),
    ]
