# Generated by Django 2.1.4 on 2019-02-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='password',
            field=models.IntegerField(blank=True, verbose_name='密码'),
        ),
    ]
