# Generated by Django 2.1.4 on 2019-02-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20190212_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='password',
            field=models.IntegerField(editable=False, null=True, verbose_name='密码'),
        ),
    ]
